image: node:16.15.0

stages:          # List of stages for jobs, and their order of execution
    - deploy

cache:
  paths:
    - front/node_modules/

build-job:       # This job runs in the build stage, which runs first.
  stage: deploy
  script:
    - cd front/
    - npm install
    - npm run build
    - rm -rf public
    - cd  ../
    - mkdir public
    - cp -r front/dist/* public
  artifacts:
  expire_in: 1 day
  paths:
    - public
  only:
    - main