image: node:16.15.0

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

cache:
  paths:
    - front/node_modules/

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd front/
    - npm install
    - npm run build
    - rm -rf public
    - cd  ../
    - mkdir public
    - cp -r front/dist/* public